name: drft_cli
description: Command-line interface for DRFT (Dart Resource Framework Toolkit)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drft:
    path: ../drft
  args: ^2.4.0
  path: ^1.8.3

